# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import main_pb2 as proto_dot_main__pb2


class SayStub(object):
    """Test the Say service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Hello = channel.unary_unary(
                '/pb.Say/Hello',
                request_serializer=proto_dot_main__pb2.Request.SerializeToString,
                response_deserializer=proto_dot_main__pb2.Response.FromString,
                )
        self.HelloStream = channel.unary_stream(
                '/pb.Say/HelloStream',
                request_serializer=proto_dot_main__pb2.Request.SerializeToString,
                response_deserializer=proto_dot_main__pb2.Response.FromString,
                )


class SayServicer(object):
    """Test the Say service
    """

    def Hello(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HelloStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Hello': grpc.unary_unary_rpc_method_handler(
                    servicer.Hello,
                    request_deserializer=proto_dot_main__pb2.Request.FromString,
                    response_serializer=proto_dot_main__pb2.Response.SerializeToString,
            ),
            'HelloStream': grpc.unary_stream_rpc_method_handler(
                    servicer.HelloStream,
                    request_deserializer=proto_dot_main__pb2.Request.FromString,
                    response_serializer=proto_dot_main__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.Say', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Say(object):
    """Test the Say service
    """

    @staticmethod
    def Hello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.Say/Hello',
            proto_dot_main__pb2.Request.SerializeToString,
            proto_dot_main__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def HelloStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/pb.Say/HelloStream',
            proto_dot_main__pb2.Request.SerializeToString,
            proto_dot_main__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
