# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import main_pb2 as main__pb2


class UserServiceStub(object):
    """User service - Comprehensive CRUD operations demonstrating all protobuf types
    This service demonstrates proper proto definition without using 'any' or 'struct' types
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateUser = channel.unary_unary(
                '/pb.UserService/CreateUser',
                request_serializer=main__pb2.CreateUserRequest.SerializeToString,
                response_deserializer=main__pb2.UserResponse.FromString,
                _registered_method=True)
        self.GetUser = channel.unary_unary(
                '/pb.UserService/GetUser',
                request_serializer=main__pb2.GetUserRequest.SerializeToString,
                response_deserializer=main__pb2.UserResponse.FromString,
                _registered_method=True)
        self.UpdateUser = channel.unary_unary(
                '/pb.UserService/UpdateUser',
                request_serializer=main__pb2.UpdateUserRequest.SerializeToString,
                response_deserializer=main__pb2.UserResponse.FromString,
                _registered_method=True)
        self.DeleteUser = channel.unary_unary(
                '/pb.UserService/DeleteUser',
                request_serializer=main__pb2.DeleteUserRequest.SerializeToString,
                response_deserializer=main__pb2.DeleteUserResponse.FromString,
                _registered_method=True)
        self.ListUsers = channel.unary_unary(
                '/pb.UserService/ListUsers',
                request_serializer=main__pb2.PageQueryRequest.SerializeToString,
                response_deserializer=main__pb2.PageUsersResponse.FromString,
                _registered_method=True)
        self.StreamUsers = channel.unary_unary(
                '/pb.UserService/StreamUsers',
                request_serializer=main__pb2.StreamQueryRequest.SerializeToString,
                response_deserializer=main__pb2.StreamUsersResponse.FromString,
                _registered_method=True)


class UserServiceServicer(object):
    """User service - Comprehensive CRUD operations demonstrating all protobuf types
    This service demonstrates proper proto definition without using 'any' or 'struct' types
    """

    def CreateUser(self, request, context):
        """Create a new user
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUser(self, request, context):
        """Get user by ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUser(self, request, context):
        """Update user
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUser(self, request, context):
        """Delete user
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListUsers(self, request, context):
        """List users with page-based pagination
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamUsers(self, request, context):
        """Stream users with cursor-based pagination
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=main__pb2.CreateUserRequest.FromString,
                    response_serializer=main__pb2.UserResponse.SerializeToString,
            ),
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=main__pb2.GetUserRequest.FromString,
                    response_serializer=main__pb2.UserResponse.SerializeToString,
            ),
            'UpdateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUser,
                    request_deserializer=main__pb2.UpdateUserRequest.FromString,
                    response_serializer=main__pb2.UserResponse.SerializeToString,
            ),
            'DeleteUser': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUser,
                    request_deserializer=main__pb2.DeleteUserRequest.FromString,
                    response_serializer=main__pb2.DeleteUserResponse.SerializeToString,
            ),
            'ListUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUsers,
                    request_deserializer=main__pb2.PageQueryRequest.FromString,
                    response_serializer=main__pb2.PageUsersResponse.SerializeToString,
            ),
            'StreamUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.StreamUsers,
                    request_deserializer=main__pb2.StreamQueryRequest.FromString,
                    response_serializer=main__pb2.StreamUsersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.UserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pb.UserService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserService(object):
    """User service - Comprehensive CRUD operations demonstrating all protobuf types
    This service demonstrates proper proto definition without using 'any' or 'struct' types
    """

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.UserService/CreateUser',
            main__pb2.CreateUserRequest.SerializeToString,
            main__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.UserService/GetUser',
            main__pb2.GetUserRequest.SerializeToString,
            main__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.UserService/UpdateUser',
            main__pb2.UpdateUserRequest.SerializeToString,
            main__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.UserService/DeleteUser',
            main__pb2.DeleteUserRequest.SerializeToString,
            main__pb2.DeleteUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.UserService/ListUsers',
            main__pb2.PageQueryRequest.SerializeToString,
            main__pb2.PageUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.UserService/StreamUsers',
            main__pb2.StreamQueryRequest.SerializeToString,
            main__pb2.StreamUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
